### ISSUE TITLE
Hello, I have a few questions here

### ISSUE THREAD

**Issue by tangzixiang-hash** [CD4017BE/RedstoneControl2#10]
Hello, I have a few questions here

1How to adjust the direction of the small square
2How to dismantle the parts in a small square structure without destroying the whole
3 Is it possible to add a workbench that allows us to arrange all the small squares on the workbench, and then we can directly place them in the world.
4 Need more clarification, I used it for almost 1 hour, but I still don’t understand how to use it

Thank you very much for your mod, and hope this mod can get better and better.
The above content comes from Google Translate, I do not speak English, sorry.

**Comment by tangzixiang-hash** [comment]
More importantly, I am confused about how to place the cables or pipes in the game.

**Comment by CD4017BE** [comment]
I just released the update adding an in-game manual. You will find the answers to your questions in chapter `Placement Tips`. In case the book doesn't explain it sufficiently, mention your problems in #4.
