### ISSUE TITLE
Gate Probe is all wonky

### ISSUE THREAD

**Issue by MoonstreamJustNotInSpace** [CD4017BE/RedstoneControl2#2]
![2021-08-23_10 04 37](https://user-images.githubusercontent.com/63458530/130461319-a9088687-93ec-4f12-9990-c5e7af100c89.png)
I can't figure out why it's doing this. Am I doing something wrong?
Modlist:
CBMultipart-1.16.5-3.0.2.119-universal.jar
car-1.16.5-1.0.17.jar
plane-1.16.5-1.0.0.jar
alchemistry-1.16.5-1.jar
cd4017be_lib-1.16.5-7.1.3.2.jar
CodeChickenLib-1.16.5-4.0.2.427-universal.jar
CodeChickenLib-1.16.5-4.0.2.429-universal.jar
Mob-Catcher-Mod-1.16.5.jar
pneumaticcraft-repressurized-1.16.5-2.13.4-215.jar
ProjectRed-1.16.5-4.10.0-core.jar
ProjectRed-1.16.5-4.10.0-exploration.jar
ProjectRed-1.16.5-4.10.0-illumination.jar
ProjectRed-1.16.5-4.10.0-integration.jar
ProjectRed-1.16.5-4.10.0-transmission.jar
redstonecontrol2-1.16.5-1.0.6.3.jar
Scorge-3.1.3.jar
create-mc1.16.5_v0.3.2b.jar
create-stuff-additions1.16.5_v1.0.6.jar
createaddition-1.16.5-20210713a.jar
flywheel-1.16-0.1.1.jar
Cucumber-1.16.4-4.1.10.jar
Disenchanting-forge-1.16.5-1.7.1.jar
entangled-1.3.4-mc1.16.5.jar
IntegratedCrafting-1.16.5-1.0.16.jar
IntegratedDynamics-1.16.5-1.9.0.jar
integratednbt-1.16.4-1.4.2.jar
IntegratedTerminals-1.16.5-1.2.4.jar
IntegratedTunnels-1.16.5-1.8.4.jar
MysticalAgradditions-1.16.4-4.1.5.jar
MysticalAgriculture-1.16.4-4.2.0.jar
MysticalCustomization-1.16.4-2.1.5.jar
NaturesAura-34.2.jar
notenoughwands-1.16-3.0.1.jar
OptiFine_1.16.5_HD_U_G8.jar
PrettyPipes-1.9.4.jar
supermartijn642configlib-1.0.8-mc1.16.jar
supermartijn642corelib-1.0.9-mc1.16.5.jar
[1.16.5]+SecurityCraft+v1.8.21.1.jar
advancedperipherals-0.6r.jar
alib-1.16.4-1.jar
appliedenergistics2-8.3.1.jar
architectury-1.12.145-forge.jar
Bookshelf-1.16.5-10.0.7.jar
Botania-1.16.5-416.jar
bperipherals-1.1.2.jar
buildinggadgets-1.16.5-3.8.0.jar
cc-tweaked-1.16.4-1.96.0.jar
chemlib-1.16.4-1.jar
chiselsandbits-0.3.4-RELEASE.jar
cofh_core-1.16.4-1.2.1.jar
CommonCapabilities-1.16.5-2.7.0.jar
create-mc1.16.5_v0.3.1c.jar
CTM-MC1.16.1-1.1.2.6.jar
curios-forge-1.16.5-4.0.5.1.jar
CyclopsCore-1.16.5-1.11.7.jar
DarkUtilities-1.16.5-8.0.9.jar
elevatorid-1.16.5-1.7.13.jar
ftb-gui-library-1605.2.1.41-forge.jar
gates-1.7.1.jar
ImmersiveEngineering-1.16.5-5.0.0-135.jar
jei-1.16.5-7.6.4.87.jar
journeymap-1.16.5-5.7.1.jar
JustEnoughResources-1.16.3-0.12.0.100.jar
kotlin_libraries-1.0-6.jar
Mantle-1.16.5-1.6.103.jar
mcjtylib-1.16-5.0.19.jar
Mekanism-1.16.5-10.0.21.448.jar
MekanismGenerators-1.16.5-10.0.21.448.jar
MekanismTools-1.16.5-10.0.21.448.jar
mightyarchitect-mc1.16.3_v0.5.jar
minecoprocessors-1.16.5-1.0.5-b1.jar
morered-1.16.5-2.1.0.2.jar
Patchouli-1.16.4-51.jar
performant-1.16.2-5-3.66m.jar
ProjectE-1.16.5-PE1.0.1B.jar
Psi+1.16-94.jar
simpleplanes-1.16.5-4.4.1.jar
Storage4ComputerCraft-1.16.4-1.2.2.jar
TConstruct-1.16.5-3.0.4.171.jar
thermal_expansion-1.16.4-1.2.0.jar
thermal_foundation-1.16.4-1.2.0.jar
thermal_locomotion-1.16.4-1.2.0.jar
tinyredstone-1.16.5-1.8.3.jar
titanium-1.16.5-3.2.8.4-10.jar
Uppers-0.3.2.jar
valkyrielib-1.16.5-3.0.8.0.jar
VendingMachine-1.16.2-1.0.0.5.jar

**Comment by CD4017BE** [comment]
Hmm, seems to be caused by Optifine, probably some optimization involving caching and reusing transformation stack matrices that my render code expected stay unchanged.
