### ISSUE TITLE
  java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by aburone** [CD4017BE/RedstoneControl2#8]
I was messing with the fluid pump.
Was having issues with the 7 section displays showing "83" an "E0" instead of the transferred amount
Flipped the clock switch and the game crashed.

https://www.toptal.com/developers/hastebin/pepehoyagi.rb

**Comment by CD4017BE** [comment]
crash fixed in [CD4017BE_lib-7.1.3.7](https://github.com/CD4017BE/CD4017BE_lib/packages/71046) (will also upload to curseforge later)

About the 7-segment display:
It displays numbers in hexadecimal (base 16), signals must go through a BCD-Converter to show up in decimal (normal base 10).
